services:
  api:
    build: .
    command: uvicorn valerie.api.main:app --host 0.0.0.0 --port 8080 --reload
    volumes: 
      - ./src:/app/src
      - ./resources:/app/resources
    env_file: .env
    ports: 
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started

  worker:
    build: .
    command: uvicorn valerie.worker.executor:app --host 0.0.0.0 --port 8081
    volumes: 
      - ./src:/app/src
      - ./resources:/app/resources
    env_file: .env
    ports: 
      - "8081:8081"
    depends_on:
      mongodb:
        condition: service_started
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: valerie
      MONGO_INITDB_ROOT_PASSWORD: localdev
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  redisdata:
  mongodata:

