"""Initial schema

Revision ID: 8c1e0fb11eb6
Revises: 
Create Date: 2026-06-05 09:18:53.065099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c1e0fb11eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apikey_key_hash'), 'apikey', ['key_hash'], unique=True)
    op.create_table('pipelinerun',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('harm_types', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('selected_techniques', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('judge_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attacker_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_api_base', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('successful_attacks', sa.Integer(), nullable=False),
    sa.Column('avg_risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluationresult',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('harm_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('technique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('adversarial_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iterations_used', sa.Integer(), nullable=False),
    sa.Column('is_breakthrough', sa.Boolean(), nullable=False),
    sa.Column('pii_leakage', sa.Boolean(), nullable=False),
    sa.Column('pii_examples', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bias', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bias_examples', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('toxicity', sa.Boolean(), nullable=False),
    sa.Column('toxicity_severity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('safety_concern', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overall_risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['pipelinerun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluationresult')
    op.drop_table('pipelinerun')
    op.drop_index(op.f('ix_apikey_key_hash'), table_name='apikey')
    op.drop_table('apikey')
    # ### end Alembic commands ###
